name: build
on:
  push:
    paths-ignore:
      - "README.md"
      - "docs"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs"
jobs:
  buildJob:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x gradlew

      # Set all the properties
      - name: Setting properties
        run: |
          echo signing.keyId=${{ secrets.KEY_ID }} >> local.properties
          echo signing.password=${{ secrets.PASSWORD }} >> local.properties
          echo ossrhUsername=${{ secrets.OSSRH_USERNAME }} >> local.properties
          echo ossrhPassword=${{ secrets.OSSRH_PASSWORD }} >> local.properties
      - name: Creating key.gpg
        id: write_file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: "key.gpg"
          encodedString: ${{ secrets.KEY_GPG }}
      - run: echo ${{ steps.write_file.outputs.filePath }}
      - run: echo signing.secretKeyRingFile=${{ steps.write_file.outputs.filePath }} >> local.properties

      # Publish libraries to local maven
      - name: Publishing libraries to local maven
        run: |
          ./gradlew navigator-extensions:publishReleasePublicationToMavenLocal
          ./gradlew navigator-base-navigation:publishReleasePublicationToMavenLocal
          ./gradlew navigator-tab-navigation:publishReleasePublicationToMavenLocal
          ./gradlew navigator-bottom-navigation:publishReleasePublicationToMavenLocal
          ./gradlew navigator:publishReleasePublicationToMavenLocal

      # Build all sample apps
      - name: Build samples
        run: |
          ./gradlew samples:basic-sample:assembleDebug
          ./gradlew samples:backpress-sample:assembleDebug
          ./gradlew samples:navigation-sample:assembleDebug

      # Test samples or code (TODO: Write tests for bottom & tab navigation)
      - name: Run Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew navigator:connectedAndroidTest
