name: build
on: [push, pull_request]
jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x gradlew

      # Publish libraries to local maven
      - name: Publishing libraries to local maven
        run: |
          ./gradlew navigator-extensions:publishReleasePublicationToMavenLocal
          ./gradlew navigator-bottom-navigation:publishReleasePublicationToMavenLocal
          ./gradlew navigator:publishReleasePublicationToMavenLocal

      # Build all sample apps
      - name: Build samples
        run: |
          ./gradlew samples:basic-sample:assembleDebug
          ./gradlew samples:backpress-sample:assembleDebug
          ./gradlew samples:bottom-navigation-sample:assembleDebug

      # Test samples or code TODO: