name: CI
on:
  push:
    paths:
      - ".github/workflows/build-compose.yml"
      - "navigator-compose/**"
  pull_request:
    paths:
      - ".github/workflows/build-compose.yml"
      - "navigator-compose/**"

defaults:
  run:
    working-directory: ./navigator-compose

jobs:
  buildAndTestJob:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          chmod +x gradlew
          chmod +x run_test.sh

      # Setting all the properties
      - name: Setting properties
        run: |
          echo signing.keyId=${{ secrets.KEY_ID }} >> local.properties
          echo signing.password=${{ secrets.PASSWORD }} >> local.properties
          echo ossrhUsername=${{ secrets.OSSRH_USERNAME }} >> local.properties
          echo ossrhPassword=${{ secrets.OSSRH_PASSWORD }} >> local.properties
      - name: Creating key.gpg
        id: write_file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: "key.gpg"
          encodedString: ${{ secrets.KEY_GPG }}
      - run: echo ${{ steps.write_file.outputs.filePath }}
      - name: Setting up properties
        run: |
          echo signing.secretKeyRingFile=${{ steps.write_file.outputs.filePath }} >> local.properties

          echo org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 > gradle.properties
          echo android.useAndroidX=true >> gradle.properties
          echo android.enableJetifier=true >> gradle.properties
          echo kotlin.code.style=official >> gradle.properties

      - uses: actions/cache@v2
        with:
          path: |
            navigator-compose/.gradle/caches
            navigator-compose/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('navigator-compose/*.gradle*') }}-${{ hashFiles('navigator-compose/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Publishing library
      - name: Publishing libraries to local maven
        run: ./gradlew navigator-compose:publishReleasePublicationToMavenLocal

      - name: Build samples
        run: |
          ./gradlew samples:basic-sample:assembleDebug

      # Test samples or code
      - name: Run Instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./navigator-compose/run_test.sh
